services:
  mysql:
    image: mysql:8.0
    container_name: backend-test-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: myhotel
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass_123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
